//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeoplesTaskApp.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PeoplesTaskApp.Langs.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ButtonAddPerson {
            get {
                return ResourceManager.GetString("ButtonAddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ButtonRemovePerson {
            get {
                return ResourceManager.GetString("ButtonRemovePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add person.
        /// </summary>
        public static string DialogTitleAddPerson {
            get {
                return ResourceManager.GetString("DialogTitleAddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit person.
        /// </summary>
        public static string DialogTitleEditPerson {
            get {
                return ResourceManager.GetString("DialogTitleEditPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; is required.
        /// </summary>
        public static string ErrorIsRequiredFormatString {
            get {
                return ResourceManager.GetString("ErrorIsRequiredFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; is out of range [{1}, {2}].
        /// </summary>
        public static string ErrorOutOfRangeFormatString {
            get {
                return ResourceManager.GetString("ErrorOutOfRangeFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; must not contain spaces.
        /// </summary>
        public static string ErrorThereIsSpacesInStringFormatString {
            get {
                return ResourceManager.GetString("ErrorThereIsSpacesInStringFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string ParameterAgePerson {
            get {
                return ResourceManager.GetString("ParameterAgePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string ParameterCityPerson {
            get {
                return ResourceManager.GetString("ParameterCityPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ParameterNamePerson {
            get {
                return ResourceManager.GetString("ParameterNamePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string ParameterSurnamePerson {
            get {
                return ResourceManager.GetString("ParameterSurnamePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove persons:
        ///{0}?.
        /// </summary>
        public static string RemovePersonQuestionFormatString {
            get {
                return ResourceManager.GetString("RemovePersonQuestionFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string TitleApp {
            get {
                return ResourceManager.GetString("TitleApp", resourceCulture);
            }
        }
    }
}
